default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.6.1
    hooks:
      - id: validate_manifest

  - repo: meta
    hooks:
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # endings
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix, lf]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext, md]

      # files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: fix-byte-order-marker

      # git
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-new-submodules

      # security
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key

  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.3"
    hooks:
      - id: poetry-check

  - repo: local
    hooks:
      - id: make-lint
        name: run make lint
        entry: make lint
        language: system
        pass_filenames: false
        types: [python]
